import { Box, Center, Container, Flex, Link, Text } from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Icon } from "@chakra-ui/react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
// import { solid, regular, brands } from '@fortawesome/fontawesome-svg-core/import.macro'
import {
  faGithub,
  faInstagram,
  faLinkedin,
} from "@fortawesome/free-brands-svg-icons";

export default function Home() {
  return (
    <>
      <Container maxW="container.xl" padding={0}>
        <Head>
          <title>My Portfolio by Steven Garman</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          {/* <Flex height="100vh" py={20}> */}
          <Box>
            <Center bg="tomato" h="100px" color="white">
              <Text fontSize="4xl">STEVEN GARMAN</Text>
            </Center>
            <Center bg="grey" h="75px" color="black">
              <Text fontSize="2xl" p={20}>
                World Traveler | Full Stack Developer
              </Text>
            </Center>
            <Center
              h="100px"
              color="black"
              border="1px"
              borderColor="black.200"
            >
              <Box>COMING SOON...</Box>
            </Center>
          </Box>
        </main>

        <Flex color="tomato" direction={"column"} align={"center"} mb={7}>
          {/* <footer className={styles.footer}> */}
          <Flex gap={4}>
            {/* <Box
              colorScheme="teal"
              _hover={{
                background: "white",
                color: "teal.500",
              }} */}
            
              <Link href="https://github.com/garman000" target="_blank" colorScheme="teal"
              _hover={{
                background: "white",
                color: "teal.500",
              }}
              >
                <FontAwesomeIcon icon={faGithub} height="30" width="30" />
              </Link>
            {/* </Box> */}
           
              <Link
                href="https://www.linkedin.com/in/stevengarman1/"
                target="_blank"
                colorScheme="teal"
              _hover={{
                background: "white",
                color: "teal.500",
              }}
              >
                <FontAwesomeIcon icon={faLinkedin} height="30" width="30" />
              </Link>
       
            
              <Link
                href="https://www.instagram.com/steven_garman/"
                target="_blank"
                colorScheme="teal"
              _hover={{
                background: "white",
                color: "teal.500",
              }}
              >
                <FontAwesomeIcon icon={faInstagram} height="30" width="30" />
              </Link>
       
          </Flex>
          <Box mt={7}>
            © 2022 Steven Garman | This site was built using NextJS
          </Box>
          {/* </footer> */}
        </Flex>
      </Container>
    </>
  );
}
